# Site settings
title: MadhavLab@IITK
general_email: madhavlab5459@gmail.com
academic_email: shivnp@iitk.ac.in

description: > # this means to ignore newlines until "baseurl:"
  Machine Analysis of Data for Human Audition and Visualization Lab
  Set up by Prof. Vipul Arora, Department of Electrical Engineering, IIT Kanpur.

baseurl: "/madhavlab" # the subpath of your site, e.g. /blog/

url: "https://shivnp.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: madhavlab
#linkedin_username: linkedin_username
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
